# Generated by Django 2.2.3 on 2019-09-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20190919_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='Time',
            new_name='time',
        ),
        migrations.AddField(
            model_name='blog',
            name='name',
            field=models.CharField(default='dfgdf', max_length=80),
            preserve_default=False,
        ),
    ]
