# Generated by Django 2.2.5 on 2019-09-30 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=300)),
                ('bank_location', models.CharField(max_length=300)),
                ('bank_logo', models.ImageField(upload_to='image/bank_logo/%Y/%m/%d')),
                ('bank_contact', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blood_quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ab_p', models.FloatField(default=0.0)),
                ('ab_n', models.FloatField(default=0.0)),
                ('a_p', models.FloatField(default=0.0)),
                ('a_n', models.FloatField(default=0.0)),
                ('b_p', models.FloatField(default=0.0)),
                ('b_n', models.FloatField(default=0.0)),
                ('o_p', models.FloatField(default=0.0)),
                ('o_n', models.FloatField(default=0.0)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood_bank.Bank_details')),
            ],
        ),
    ]
