# Generated by Django 2.2.5 on 2019-10-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_details',
            name='owner',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
