# Generated by Django 2.2.5 on 2019-10-22 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0002_bank_details_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_details',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
