# Generated by Django 2.2.5 on 2019-09-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/slide_show/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
