# Generated by Django 2.2.3 on 2019-09-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=45, unique=True)),
                ('username', models.CharField(max_length=45)),
                ('blood_group', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('present_add', models.TextField(max_length=200)),
                ('last_date_of_donation', models.DateField(max_length=50)),
                ('permanent_add', models.TextField(max_length=200)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
